#!/usr/bin/env bash

JAVA_MAJOR=11
JAVA_MINOR=0
APP_JAR="plugins/org.eclipse.equinox.launcher-1.5.200.jar"
APP_NAME="IMPAX EE CD Viewer for MAC"
VM_ARGS="-Dsun.java2d.d3d=false -server -Xverify:none -Dsun.awt.nopixfmt=true -Dawt.touchKeyboardAutoShowIsEnabled=false -Dsun.java2d.uiScale=1.0 -Djava.util.PropertyResourceBundle.encoding=ISO-8859-1 --illegal-access=permit --patch-module java.desktop=modules/patch/com.agfa.pacs.thirdparty.java.desktop.patch.jar -Dosgi.user.area=@none -Dosgi.configuration.area=@none -Dosgi.instance.area=@none"

# Set the working directory to be CD/DVD root
cd "$(dirname "$0")/../../../"

# Error message for NO JAVA dialog
ERROR_TITLE="Cannot launch $APP_NAME"
ERROR_MSG="$APP_NAME benoetigt Java version $JAVA_MAJOR.$JAVA_MINOR oder neuer."
DOWNLOAD_URL="https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot"


# Is Java installed?
if type -p java; then
    _java="java"
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
    _java="$JAVA_HOME/bin/java"
else
    osascript \
	-e "set question to display dialog \"$ERROR_MSG\" with title \"$ERROR_TITLE\" buttons {\"Cancel\", \"Download\"} default button 2" \
	-e "if button returned of question is equal to \"Download\" then open location \"$DOWNLOAD_URL\""
	echo "$ERROR_TITLE"
	echo "$ERROR_MSG"
	exit 1
fi

# Java version check
if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    if [[ "$version" < "$JAVA_MAJOR.$JAVA_MINOR" ]]; then
        osascript \
    	-e "set question to display dialog \"$ERROR_MSG\" with title \"$ERROR_TITLE\" buttons {\"Cancel\", \"Download\"} default button 2" \
    	-e "if button returned of question is equal to \"Download\" then open location \"$DOWNLOAD_URL\""
       	echo "$ERROR_TITLE"
    	echo "$ERROR_MSG"
    	exit 1
    fi
fi

# Run the application
exec $_java  $VM_ARGS -Dapple.laf.useScreenMenuBar=true -Dcom.apple.macos.use-file-dialog-packages=true -Xdock:name="$APP_NAME" -Xdock:icon="./CDViewerMac/Contents/Resources/Agfa.icns" -jar "$APP_JAR" -application com.agfa.pacs.login.LoginManager -clear